name: Push to Docker Hub

on:
  push:
    paths-ignore:
      - '**.rst'
    branches:
      - master

jobs:
  build-cpu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push CPU image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ucberkeleyseti/turbo_seti
          tags: latest

  build-gpu:

    runs-on: nvidia-gpu

    steps:
      - uses: actions/checkout@v2
      - name: Build and push GPU image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ucberkeleyseti/turbo_seti_gpu
          build_args: IMAGE=cupy/cupy:v8.6.0
          tags: latest
